name: CI # Workflow的名称
 
on: # 触发条件
  push:
    branches: [ main ] # 当代码推送到main分支时触发
  pull_request:
    branches: [ main ] # 当创建或更新pull request到main分支时触发
 
jobs: # 定义jobs
  build: # job的名称
    runs-on: ubuntu-latest # 指定运行环境，这里是最新版的Ubuntu
    steps: # 定义步骤
    - uses: actions/checkout@v2 # 检出代码
    - name: Set up Node.js
      uses: actions/setup-node@v2 # 设置Node.js环境
      with:
        node-version: '14' # 设置Node.js版本
    - run: npm install # 安装依赖
    - run: npm run build # 构建项目
    - run: npm test # 运行测试
